apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneDelivery
  labels:
    app: droneDelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: droneDelivery
  template:
    metadata:
      labels:
        app: droneDelivery
    spec:
      containers:
        - name: droneDelivery
          image: username/droneDelivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5