apiVersion: apps/v1
kind: Deployment
metadata:
  name: cscenter
  labels:
    app: cscenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cscenter
  template:
    metadata:
      labels:
        app: cscenter
    spec:
      containers:
        - name: cscenter
          image: username/cscenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5